name: tests_sprint_9
on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  checkout-and-run-tests:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Pull browser image
        run: docker pull selenoid/vnc:chrome_128.0

      - name: Run tests in docker
        run: docker compose up --build --exit-code-from tests

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 5

      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: always()

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
            path: 'allure-history'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()